DEFAULT_FG_COLOR_CHANGE="%{$fg[black]%}"

export PROMPT_ICON_GIT_BRANCH=""
export PROMPT_ICON_GIT_MERGING=""
export PROMPT_ICON_GIT_UNTRACKED=" "
export PROMPT_ICON_GIT_STAGED=" "
export PROMPT_ICON_GIT_AHEAD=" "
export PROMPT_ICON_GIT_BEHIND=" "
export PROMPT_ICON_PYTHON=" "
